ranks:
  basic:
    name: "Básico"
    prefix:
      short: "[B] "
      long: "[Basic] "
    commands:
      - "pex user {name} group remove {currentRank}"
      - "pex user {name} group add {newRank}"
    position: 1
  advanced:
    name: "Avançado"
    prefix:
      short: "[A] "
      long: "[Advanced] "
    commands:
      - "pex user {name} group remove {currentRank}"
      - "pex user {name} group add {newRank}"
    position: 2
    price: 500